contribute/partners/cloud-resources.md
Signed-off-by: Roman Hros <roman.hros@dnation.cloud>
=> Add dNation Dev Project cloud resource

community/contribute/cloud-resources/cloud-resources.md
Hi,
please provide me a project so I can do tests on and with the k8s-cluster-api-provider. I tried doing tests in another projects but went in conflicts because of already existing resources which is a blocker when doing full tests.
Signed-off-by: Jan Schoone <jan@jass.es>
=> Add kaas project

community/contribute/license-considerations.md
ref: SovereignCloudStack/docs#4
Signed-off-by: Ralf Heiringhoff <ralf.heiringhoff@plusserver.com>
=> fix broken links

community/contribute/license-considerations.md
ref: SovereignCloudStack/docs-page#33 SovereignCloudStack/docs-page#34
Signed-off-by: Ralf Heiringhoff <frosty-geek@users.noreply.github.com>
=> fix typos in license-considerations.md

community/contribute/cloud-resources/cloud-resources.md
Please provide us a cloud resource project to implement the SCS metering  tender
=> Adds the meetering Projects cloud resource allocation.

community/contribute/adding-docs-guide.md, community/contribute/doc-files-structure-guide-md, community/contribute/docs-workflow-explanation.md, community/contribute/local-docusaurus-development-guide.mdx, community/contribute/styleguide.md
As discussed in today's SIG Documentation I created the first version of guides and explanations. Please comment and correct. Thank you!
=> Add Doc Guides

community/cloud-resources/cloud-resources.md
Hi,
we need two more environments. One is for a tender to work on the Network and Storage Interfaces for Kubernetes. 
Thank you :cloud:
=> Add openstack projects for tender vp06a

operations/iaas/metering/meter_configuration.md
to push raw events to the metering api
=> fixes event pipeline to metering

community/cloud-resources/cloud-resources.md
Hi Ralf, Markus,
this is a request for a project for MineryReport. They are the company that is working on tender VP09a (PenTesting) for us.
The intention is to build a Testbed IaaS deployment in the requested with keycloak and optionally k8s on top to do pentesting against.
We need (at least) two users to be able to access it, David Rodriguez Regueira @90n20 and Miguel Angel Romero de los Llanos @Seykotron.
Thanks!
=> Add request for project for Minery Report (Pentesting).

docusaurus.config.js
=> Fix repo name

.gitignore, docs.package.json, docs/02-iaas/deployment-examples/a/hardware.md, docs/02-iaas/deployment-examples/a/index.md, docs/02-iaas/deployment-examples/a/software.md, docusaurus.config.js, sidebarsDocs.js
This is a stop-gap measure until we have the news docs.
=> Readd (old) testbed and ciab docs as 02-iaas/deployment-examples.

community/cloud-resources/cloud-resources.md
Requesting an openstack project to use it for the develpoment of the conformance tests.
=> Request cloud resource

community/cloud-resources/cloud-resources.md
Request user on plusserver SCS cloud for Anja Strunk
=> Request user for anjastrunk

docs/08-faq/index.mdx
=> Fix links in FAQ

README.md
fixing a typo which was created in last PR
=> Fixing a typo in readme.md

populateStds.js
resolves [standards/#446](https://github.com/SovereignCloudStack/standards/issues/446)
=> Bugfix: standard version being showed both stable and deprecated

community/central-services/plusserver-gx-scs.md
Fixes SovereignCloudStack/issues#516
=> Add central services managed by dNation

community/cloud-resources/cloud-resources.md
cc @SovereignCloudStack/plusserver
=> Update cloud-resources.md, add bitkeks project

docs/08-faq/index.mdx
Signed-off-by: Sven Kieske <kieske@osism.tech>
=> fix two broken links in the faq

.gitignore, docs.package.json, docs/04-operating-scs/01-guides/guide-1.md, sidebarsDocs.js
This should address #147, once complete.
=> Add OS Health Mon setup guide.

src/components/ContentCard.tsx
=> Fix display of components in Architectual overview 

docs/05-iam/SCS-example-setup-configuration-description.md, sidebarsDocs.js
Pull request using local branch instead of fork.
https://github.com/SovereignCloudStack/docs/pull/190
=> Added documentation about example setup

populateStds.js
Removed the "Stable" column from tables and introduced * markers for future effective documents and † for future deprecated documents.
I also changed the legend according to the new implementations.
closes #215
=> Simplify standards overview table

docs.package.json, sidebarsDocs.js
- Ref: #207 
- Ref: SovereignCloudStack/issues#720
=> Feat: Add status-page-web docs

sidebarsUserDocs.js, static/data/additionalResourcesData.json
* fix deployment examples link
* add application examples
=> Update additional resource on landing page

docs/03-container/index.md
=> docs(🧀): update container index

community/cloud-resources/cloud-resources.md
The latter is required without time limit.
=> Add monitoring project. kaas-hack3 is for moin.

docs.package.json
=> OSISM PR #805 has broken our testbed docs build process.
