- community/contribute/adding-docs-guide.md
- community/contribute/docs-workflow-explanation.md
Just minor things I'd consider to adjust. All in all, after reading this document, that I feel like I do understand how the mechanism works, so thanks for sharing!
---
Regarding the changes to the inline JSON:
1. As plain JSON does not support comments (but this example of course benefits from comments), using `json5` as format of the code block results in a nicer visual rendering - even though it will not be valid plain JSON either way.
2. I'd usually expect comments to be above the thing that they are commenting on - not below.
3. (not touched by this PR:) The comments could be maybe a bit more precise regarding the type of data which is to be expected.
- `link to github organisation and repository` has `demo-organisation/demo-repository` as example, which is not a link per se.
- …
> Fix minor issues in contribute docs

- community/contribute/adding-docs-guide.md
Remove problematic `,`; Add necessary `"`.
> Fix JSON syntax in adding-docs-guide.md

- community/hackathons/checklist.md
This Patch provides a list for planning hackathons.
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Add checklist for Hackathon planning

- .markdownlint-cli2.jsonc
- community/hackathons/checklist.md
fixes #38 
`<ul><li>- [ ] </li></ul>`
instead of 
`<input type="checkbox" id="checkbox1">`
> Fix inline html for checkboxes and adjust rules

- community/contribute/styleguides/ansible_styleguide.md
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Add ansible-styleguide

- docs/03-container/index.md
- sidebarsDocs.js
written by @fdobrovolny – Thanks!
As discussed in the SIG Docs, adding some more information of the upcoming cluster-stacks would be great.
closes #95
> Add Container Introduction

- dev-docs/operations/iam/identity-federation-in-scs.md
During the initial commit for https://github.com/SovereignCloudStack/docs/pull/72 the final location of the documents was unkown and then it was merged into a dev-docs folder, so now the link points to an entirely unintended section of the SCS documentation, making it inaccessible and adding to confusion rather than fulfilling its original intention.
> fix link to documentation about the identity federation concept in SCS

- docs.package.json
The image manager docs now need additional files, which haven't been copied in the build process.
Resolves #120
> Fix build and make it less brittle (hopefully)

- community/collaboration.md
This should give an overview over the structure of meetings, but the precise times should not be duplicated here. Rather refer to the public calendar. Being at it, also clarify a few details on Nextcloud etc.
> Reference public calendar instead of duplicating meeting info

- community/cloud-resources/cloud-resources.md
For E2E tests for KaaS v1 we reuse project **p500924-gxhackathon6-1**(it was not deleted in #31 and was not created in #42).
I put myself as a *Community Contact* and changed *Needed until* ∞ for this project.
Can you also change the project name and description there?
E.g.(according to #42):
- *Project Name*: from **p500924-gxhackathon6-1** to **scs-k8s-e2e**
- *Description*: from **Gaia-X Hackathon 6 Projekt1** to **E2E-Test for KaaS**
Related to SovereignCloudStack/issues#516
> Add openstack project for e2e tests for kaas v1

- community/cloud-resources/cloud-resources.md
This project now hosts the productive monitoring cluster, hence we need to keep it alive
> Update p500924-sig-monitoring1 'needed until' date

- contributor-docs/operations/operations/zuul-ci-cd-quickstart-user-guide.md
This PR notifies SCS Zuul users about the activation of reporting to the Matrix chat room `SCS | Zuul Reports` for periodic pipelines (periodic-hourly, periodic-daily, compliance_check). Additionally, it includes an example demonstrating how to configure MQTT reporting in the pipeline.
> Add reports section to the Zuul user guide

- docs.package.json
- sidebarsDocs.js
- static/data/architecturalOverviewData.json
This PR adds container registry docs and display container registry on the overview map
Related to https://github.com/SovereignCloudStack/docs/issues/136
> Add container registry docs and display it on the overview map

- docs.package.json
- sidebarsDocs.js
- static/data/architecturalOverviewData.json
This PR adds monitoring docs and displays the monitoring on the overview map
Related to https://github.com/SovereignCloudStack/docs/issues/136
@maxwolfs 
The monitoring box does not fit the Ops Layer box on the overview map, see here:
What are your preferences here? i.e.: resize the ops layer box only or resize the entire component map?...
> Add monitoring docs and display it on the overview map

- docs/05-iam/index.md
Add role limitation explanatiion to docs
https://github.com/SovereignCloudStack/issues/issues/360
> Document federated users role limitation #360

- community/contribute/styleguide.md
I updated the broken link to point to the docs for the 2.4.3 release [that we currently use](https://github.com/SovereignCloudStack/docs/blob/ff164f25e044c4126f21d9810f2b1ec5f86dc661/package-lock.json#L13).
Note that the unrelated syntax changes in the code blocks were integrated automatically by the pre-commit hook linter.
> Fix orphaned link to Docusaurus docs about admonition banners

- populateCerts.js
- populateStds.js
(deprecated_at instead of obsoleted_at)
see https://github.com/SovereignCloudStack/standards/commit/947fa5e57a25266456ae315a718266f67c3d2da5
> Adjust populateStds.js and populateCerts.js to renamed field

- community/central-services/plusserver-gx-scs.md
Related to SovereignCloudStack/k8s-harbor#64
> Upgrade k8s that hosts SCS Registry to R6

- docs.package.json
- sidebarsDocs.js
- static/data/architecturalOverviewData.json
Depends on https://github.com/SovereignCloudStack/central-api/pull/7
> Add Central API in Ops

- docs.package.json
- sidebarsDocs.js
- static/data/architecturalOverviewData.json
Adding the missing docs about all parts the status page.
Closes: SovereignCloudStack/issues#610
> Feat: Add status page docs

- .gitignore
- populateStds.js
- standards/index.md
Added the color mapping with a react component. Needed to change the overview.md file to .mdx format.
related issue: [445](https://github.com/SovereignCloudStack/standards/issues/445)
> Add color coding to the to standards table in the docs page

- populateStds.js
* Add misssing `trim()` to avoid double white spaces in standards generation code
as seen here: https://github.com/SovereignCloudStack/docs/actions/runs/10042568134/job/27850074200?pr=87#step:6:14
> Fix Linting Errors

- community/central-services/plusserver-gx-scs.md
Add also SSD flavors for the control-plane
Related to SovereignCloudStack/k8s-observability#72, SovereignCloudStack/k8s-observability#73 and SovereignCloudStack/k8s-harbor#68
> Upgrade k8s that hosts SCS monitoring to R6

- populateStds.js
I added redundant color coding to other tables in the documentation.
Now it should be applied not only to the overview table, but also to all other detailed tables (IaaS, IAM, etc.).
closes #216
> Added redundant color coding to other tables in the documentation

- docs.package.json
- sidebarsDocs.js
> Improve kaas documentation

- docs.package.json
- sidebarsDocs.js
- static/data/architecturalOverviewData.json
Integrates the KaaS security tooling docs into the docs.
Rename previously added "automated-pentesting" entry to "-iaas" and add "-kaas". Both sections are now under-categories and are both displayed in the component overview.
> feat(security): Add KaaS pentesting tools to docs

- package-lock.json
> Fix/update ws, path-to-regexp, micromatch

- .markdownlint-cli2.jsonc
- docusaurus.config.js
* remove `standards` repo from being linted in this repo, which leads to unnecessary failing checks
* change onBrokenLinks (docusaurus internal checker during each build process, which is separate to our additional markdown-lint-checker) behavior from `throw` to `warn` to allow relative links from docs of external repo (so even more important to read the logs carefully once a build does not succeed)
> Adjust checks: linter and link checker  

- docs/index.mdx
The wording was probably a year old, still talking about previews ...
> KaaS v2 (Cluster Stacks) has fully replaced v1.

- sidebarsUserDocs.js
Fix only a small spelling issue in *openDesk*.
Thank you for creating this guide!
> Fix spelling of openDesk

- docs/05-iam/iaas-roles.md
Part of https://github.com/SovereignCloudStack/issues/issues/396
> Document IaaS roles

- static/data/featureContentData.json
Also use the term reference implementation, trying to avoid confusion by having clear and consistent terminology.
> Latest is R8, not R7.

- docs.package.json
- sidebarsDocs.js
We plan to deprecate the CSPO from R8 in favor of the image kind of the OpenStack Resource Controller (ORC).
For archived docs, the CSPO repo can be mentioned.
Should me merge not before `images.openstack.k-orc.cloud` has been added to the Cluster Stacks.
> Remove Cluster Stack Provider OpenStack

- .github/workflows/build_and_deploy.yml
From 0 am UTC to 5 am UTC, which is 7 am CEST.
Vastly increases the chance that we catch the latest nightly results from the compliance checks, in particular when they are moved back from 3 am UTC to 0 am UTC, as proposed in a concurrent PR: https://github.com/SovereignCloudStack/zuul-scs-jobs/pull/49
> Move docs build forward 5 hrs
